apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ntd0x1cc4-nodejs 
  janus-idp.io/tekton: ntd0x1cc4-nodejs
  backstage.io/kubernetes-id: ntd0x1cc4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntd0x1cc4-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml