apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ntd0x1cc4-nodejs
  janus-idp.io/tekton: ntd0x1cc4-nodejs
  backstage.io/kubernetes-id: ntd0x1cc4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntd0x1cc4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
